import { NextPage } from "next";
import Head from "next/head";
import NavBar from "../components/NavBar";
import Header from "../components/Header";
import About from "../components/About";
import Skills from "../components/Skills";
import Work from "../components/Work";
import Contact from "../components/Contact";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Jonathan Tellkampf | Full stack web developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="app">
        <NavBar />
        <Header />
        <About />
        <Skills />
        <Work />
        <Contact />
      </div>
    </>
  );
};

export default Home;
